# Generated by Django 5.1.3 on 2024-11-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0002_stock_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='invoice_date',
        ),
    ]
