# Generated by Django 5.1.3 on 2024-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0003_remove_product_invoice_remove_product_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.TextField(blank=True, max_length=100)),
                ('invoice_date', models.DateTimeField(blank=True)),
                ('stock_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('supplier_id', models.IntegerField(blank=True)),
                ('technician_id', models.IntegerField(blank=True)),
                ('classification', models.TextField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
