# Generated by Django 5.1.3 on 2025-01-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0005_alter_history_invoice_alter_history_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='technician',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
