# Generated by Django 5.1.3 on 2025-01-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0006_product_active_stock_active_supplier_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='for_use',
            field=models.BooleanField(default=0),
        ),
    ]
