# Generated by Django 5.1.3 on 2024-11-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_login_creation_date_user_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user',
            new_name='email',
        ),
    ]
